server:
  port: 8081

spring:
  application:
    name: Cache_Library_Application
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000

  datasource:
    url: jdbc:postgresql://localhost:5432/springjdbc?currentSchema=cachelibapp
    username: postgres
    password: 19111011
    driver-class-name: org.postgresql.Driver